import { RootState as RootStateType } from "@/lib/redux";

export type RootState = RootStateType;

export interface User {
  id: string;
  user_id: string;
  name: string;
  password: string;
  email?: string;
  employee_id?: string;
  phone?: string | null;
  position?: string | null;
  type?: string;
  school_id?: string | null;
  staff_category_code?: string | null;
  gender?: string | null; // staff sex, migration 146
  learning_area?: string | null; // teaching specialization, migration 146
  is_active: boolean;
  created_at?: string;
}

export interface AddUserFormValues {
  name: string;
  email: string;
  type: string;
  is_active: boolean;
}

export type {
  Barangay,
  Book,
  Evaluation,
  EvaluationQuestion,
  EvaluationRespondentType,
  EvaluationResponse,
  EvaluationType,
  BookAllocation,
  BookIssuance,
  BookReturnCode,
  ClassRecord,
  ClassRecordComponent,
  ClassRecordItem,
  ClassRecordScore,
  CrlaMaterial,
  CrlaMaterialTask,
  CrlaBand,
  CrlaRecord,
  CrlaRecordScore,
  CrlaRecordForm,
  CrlaRecordFormLine,
  CrlaRecordFormObservation,
  CrlaRecordFormRecord,
  CrlaRecordFormLineScore,
  PhilIriMaterial,
  PhilIriQuestion,
  PhilIriRecord,
  PhilIriComprehensionAnswer,
  PhilIriAnswer,
  RmaMaterial,
  RmaItem,
  RmaBand,
  RmaRecord,
  RmaItemScore,
  PabasaRecord,
  AralEnrollment,
  AralTutor,
  AralProgram,
  AralTier,
  AralStatus,
  AralSourceAssessment,
  AralAttendanceDate,
  AralAttendanceMark,
  AralAttendanceStatus,
  AralProgressSession,
  AralProgressMark,
  AralProgressLevel,
  AnecdotalRecord,
  CardexNeed,
  CardexCommunication,
  CardexCommMode,
  ManifestationTag,
  ManifestationTagItem,
  ManifestationIntervention,
  ManifestationClassType,
  ManifestationConsentStatus,
  ManifestationInterventionStatus,
  NonGradedProgram,
  LsenCategory,
  DoctorItem,
  DocumentTracker,
  EccdAssessment,
  EccdCompetency,
  EccdDomain,
  EccdPeriod,
  EccdScaleScore,
  Enrollment,
  EnrollmentLifecycleStatus,
  FamilyCompositionItem,
  Grade,
  Hospital,
  LearnerHealth,
  Lot,
  LotItem,
  LrnLookupResult,
  MPSEntry,
  MedicalAssistance,
  PurchaseOrder,
  RecordRequest,
  RecordRequestStatus,
  ClassSizeStandard,
  Room,
  RoomCondition,
  School,
  StaffCategory,
  StaffCategoryCode,
  Section,
  SectionSubject,
  SectionType,
  Student,
  StudentEntryMode,
  StudentSubject,
  Subject,
  SubjectSchedule,
  Tos,
  TosCompetency,
  TosItem,
  TosCognitiveLevel,
  Exam,
  ExamQuestion,
  ExamOption,
  ExamSubitem,
  ExamSection,
  ExamResult,
  ExamResultStudent,
  ExamQuestionKind,
  ExamAnswerKey,
  ExamScanSource,
  SrcStatus,
  SrcSectionKey,
  SrcAwardLevel,
  SrcAwardCategory,
  SrcSignatory,
  SrcSignatoryRole,
  SrcEnrollmentRow,
  SrcHealthRow,
  SrcMaterialRow,
  SrcProfessionalDevelopmentRow,
  SrcPartnerRow,
  SrcContributionRow,
  SrcAwardRow,
  SrcRateRow,
  SrcDropoutCauseRow,
  SrcPerformanceRow,
  SrcParticipationRow,
  SrcRatioRow,
  SrcSectionPayloadMap,
  SrcSubmission,
  SrcSection,
  SrcAutofill,
  KpiReference,
  KpiEnrollmentFact,
  KpiResourceFact,
  SupervisionObserver,
  SupervisionPlan,
  SupervisionPlanEntry,
  SupervisionSchedule,
  SupervisionScheduleObserver,
  SupervisionScheduleStatusValue,
  SupervisionTypeValue,
  CareerStageValue,
  CotObservation,
  CotFormKindValue,
  CotRating,
} from "./database";
